name: beidou-nas

services:
  beidou-server-all:
    container_name: beidou-server-all
    image: ghcr.io/beidoums/beidou-server-all:v1.12
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: "-XX:+UseZGC -XX:+ZGenerational -XX:+UseStringDeduplication -Xms1024m -Xmx2048m"
    ports:
      # 登录服务器
      - "8484:8484"
      # 频道 1 ~ 3
      - "7575-7577:7575-7577"
    volumes:
      - ./beidou-server-release:/opt/server
    command: 
      - --mybatis-flex.datasource.mysql.url=jdbc:mysql://beidou-db:3306/beidou?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      - --mybatis-flex.datasource.mysql.username=root
      - --mybatis-flex.datasource.mysql.password=root
      - --gms.service.wan-host=${SERVER_HOST:-192.168.1.57}
      - --gms.service.lan-host=${SERVER_HOST:-192.168.1.57}
      - --gms.service.localhost=127.0.0.1
    depends_on:
      beidou-db:
        condition: service_healthy
    networks:
      beidou-network:
        aliases:
          - beidou-server

  beidou-ui:
    container_name: beidou-ui
    image: ghcr.io/beidoums/beidou-ui:nightly
    restart: unless-stopped
    ports:
      # Web 控制台与 API 反代
      - "8686:8686"
    depends_on:
      - beidou-server-all
    networks:
      - beidou-network

  beidou-db:
    container_name: beidou-db
    image: mysql:8.4.0
    restart: unless-stopped
    environment:
      # mysql root 默认密码
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      # 局域网访问或管理工具连接
      - "3306:3306"
    volumes:
      - ./docker-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - beidou-network

networks:
  beidou-network:
    driver: bridge
